require:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test'
    - 'spec/**/*'
Layout/SpaceInLambdaLiteral:
   Enabled: false
Lint/AmbiguousOperator:
  Exclude:
    - 'Rakefile'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/CollectionMethods:
  Enabled: true
Style/FormatString:
  EnforcedStyle: percent
Style/SignalException:
  EnforcedStyle: only_raise
Style/StabbyLambdaParentheses:
   Enabled: false