require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "test"
  NewCops: enable
Layout/BeginEndAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/LineLength:
  Enabled: false
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInLambdaLiteral:
  Enabled: false
Lint/AmbiguousOperator:
  Exclude:
    - "Rakefile"
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'factories/**/*.rb'
    - 'spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'factories/**/*.rb'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 15
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Rake/DuplicateTask:
  Enabled: false
RSpec/ExampleLength:
  Enabled: False
RSpec/ExpectInHook:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/CommandLiteral:
  EnforcedStyle: percent_x
Style/ExponentialNotation:
  Enabled: true
Style/FormatString:
  EnforcedStyle: percent
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ParallelAssignment:
  Enabled: false
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SignalException:
  EnforcedStyle: only_raise
Style/SlicingWithRange:
  Enabled: true
Style/StabbyLambdaParentheses:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
