require:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test'
    - 'spec/**/*'
Layout/LineLength:
    Max: 120
Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented
Layout/SpaceInLambdaLiteral:
    Enabled: false
Lint/AmbiguousOperator:
  Exclude:
    - 'Rakefile'
Metrics/MethodLength:
  Max: 15
Style/CollectionMethods:
  Enabled: true
Style/FormatString:
  EnforcedStyle: percent
Style/ParallelAssignment:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/SymbolArray:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
