#!/usr/bin/env ruby

require 'highline/import'
require 'trollop'
require_relative 'lib/diary'

include Diary

if __FILE__==$0
  opts = Trollop::options do
    banner "Create feedback entry for a person"
  end

  person = ARGV[0]
  record_to_file :feedback, person
end
