#!/usr/bin/env ruby

require 'pathname'
require 'trollop'
require 'facets/string/titlecase'
require_relative 'lib/employee_folder'
require_relative 'lib/path_splitter'

extend PathSplitter

class String
  def titleize
    split(/(\W)/).map(&:capitalize).join
  end
end

if __FILE__==$0
  opts = Trollop::options do
    banner "Generate the files needed to create a team overview"
    opt :force, 'generate even if file exists', :default => false
  end

  Dir.glob("#{EmployeeFolder.root}/*/*") do |f|
     next unless Dir.exist? f
     paths = split_path f
     first, last = paths[2].gsub!('-', ' ').titleize.split(' ')
     force = if opts[:force] then "--force" else "" end
     system('./mt', 'new-hire', force, "--team", "#{paths[1]}", "--first", "#{first}", "--last", "#{last}") or exit(-1)
  end
end
