#!/usr/bin/env ruby

require 'pathname'
require 'trollop'
require 'facets/string/titlecase'
require_relative 'lib/employee'
require_relative 'lib/employee_folder'
require_relative 'lib/mt_data_formatter'
require_relative 'lib/path_splitter'

extend MtDataFormatter
extend PathSplitter

if __FILE__ == $PROGRAM_NAME
  opts = Trollop.options do
    banner 'Generate the files needed to create a team overview'
    opt :force, 'generate even if file exists', default: false
  end

  force = opts[:force] ? '--force' : ''
  Dir.glob("#{EmployeeFolder.root}/*/*") do |folder|
    next unless Dir.exist? folder
    employee = Employee.find(folder)
    args = %w(new-hire) << force
    %w(team first last).each do |p|
      args << "--#{p}"
      args << "#{employee.send(p.to_sym)}"
    end
    system('./mt', *args) || exit(-1)
  end
end
