#!/usr/bin/env ruby

require 'configatron'
require 'fileutils'
require 'trollop'
require_relative 'lib/employee'
require_relative 'lib/employee_file'

def generate_file(folder, overview_file)
  contents = <<EOF
:imagesdir: #{folder.path}

== #{folder.employee}

image::headshot.jpg[#{folder.employee}, width="200", align="right", float="right"]

Team: #{folder.employee.team.capitalize}

EOF
  print "generating\n"
  File.open(overview_file.path, 'w') do |f|
    f.write(contents)
  end
end

if __FILE__==$0
  opts = Trollop::options do
    opt :force, 'generate even if file exists'
    opt :team, 'team name (like avengers)', :type => :string, :required => true
    #opt :name, 'person\'s full name (in quotes, like "Tony Stark")', :type => :string
    opt :first, 'person\'s first name (in quotes, like "Tony Stark")', :type => :string
    opt :last, 'person\'s last name (in quotes, like "Tony Stark")', :type => :string
  end

  # if opts[:name].nil? and (opts[:first].nil? or opts[:last].nil?)
  #   puts "either --name or both --first and --last are required, don't know how to proceed without them"
  #   puts opts
  #   exit(1)
  # end

  #puts "\nDEBUG: opts = #{opts}\n"
  team = opts[:team]
  first = opts[:first]
  last = opts[:last]
  #first, last = opts[:name].split(' ')
  #warn "WARN: First name missing" if first.nil?
  #warn "WARN: Last name missing" if last.nil?

  employee = Employee.new({ team: team, first: first, last: last })
  folder = EmployeeFolder.new employee
  folder.ensure_exists

  overview_file = EmployeeFile.new folder, "overview.adoc"
  print "\nReviewing #{overview_file}... "
  if (not opts.force?) and File.exist? overview_file.path
    print "exists\n"
  else
    generate_file folder, overview_file
  end

  log_file = EmployeeFile.new folder, "log.adoc"
  log_file.ensure_exists
end
