#!/usr/bin/env ruby

require 'configatron'
require 'fileutils'
require 'trollop'
require_relative 'lib/employee'
require_relative 'lib/employee_file'

def generate_file(folder, overview_file)
  contents = <<EOF
:imagesdir: #{folder.path}

== #{folder.employee}

image::headshot.jpg[#{folder.employee}, width="200", align="right", float="right"]

Team: #{folder.employee.team.capitalize}

EOF
  print "generating\n"
  File.open(overview_file.path, 'w') {|f| f.write(contents) }
end

if __FILE__==$0
  opts = Trollop::options do
    opt :force, 'generate even if file exists'
    opt :team, 'team name (like avengers)', :type => :string
    opt :name, 'person\'s name (in quotes, like "Tony Stark")',
      :type => :string
  end

  if opts[:team].nil? or opts[:name].nil?
    puts "--team and --name are required, don't know how to proceed without them"
    puts opts
    exit(1)
  end

  team = opts[:team]
  first, last = opts[:name].split(' ')

  employee = Employee.new({ team: team, first: first, last: last })
  folder = EmployeeFolder.new employee
  folder.ensure_exists

  overview_file = EmployeeFile.new folder, "overview.adoc"
  print "\nReviewing #{overview_file}... "
  if (not opts.force?) and File.exist? overview_file.path
    print "exists\n"
  else
    generate_file folder, overview_file
  end

  log_file = EmployeeFile.new folder, "log.adoc"
  puts "\nTouching #{log_file}... "
  FileUtils.touch(log_file.to_s)
end
