#!/usr/bin/env ruby

require "highline/import"
require 'trollop'
require_relative 'lib/diary'

include Diary

if __FILE__==$0
  opts = Trollop::options do
    banner "Make an observation about a person"
  end
  person = ARGV[0]
  record_to_file :observation, person
end
