#!/usr/bin/env ruby

require 'trollop'
require_relative 'lib/diary'

include Diary

if __FILE__ == $PROGRAM_NAME
  Trollop.options do
    banner 'Open a person\'s log file'
  end

  person = ARGV[0]
  employee = Employee.get person
  log_file = employee.file
  log_file.ensure_exists
  exec("open #{log_file}")
end
