#!/usr/bin/env ruby

require 'highline/import'
require 'shell'
require 'trollop'
require_relative 'lib/diary'

include Diary

def append_file(destination, input)
  contents = IO.read(input)
  open(destination, 'a') do |f|
    f.puts contents
    f.puts '\n'
  end
end

if __FILE__ == $PROGRAM_NAME
  Trollop.options do
    banner 'Create a report from a person\'s files'
  end

  person = ARGV[0]
  employee = get_employee person

  folder = EmployeeFolder.new employee
  folder.ensure_exists

  overview_file = File.join(folder.path, 'overview.adoc')
  log_file = (LogFile.new folder).to_s
  report_source = 'report.adoc'
  output = 'report.html'

  [report_source, output].each do |file|
    File.delete file if File.exist? file
  end

  append_file(report_source, overview_file)
  append_file(report_source, log_file)

  system('asciidoctor', '-o#{output}', report_source)
  system('open', output) # for Mac, use 'cmd /c' for Windows
end
