#!/usr/bin/env ruby

# Should do a './gen-overview-files' before this to ensure overview files exist

require 'facets/string/titlecase'
require 'highline/import'
require 'shell'
require 'trollop'
require_relative 'lib/mt_data_formatter'
require_relative 'lib/team'

extend MtDataFormatter

def append_file(destination, contents)
  open(destination, 'a') do |f|
    f.puts contents
    f.puts "\n"
  end
end

if __FILE__ == $PROGRAM_NAME
  Trollop.options do
    banner 'Create a report of a team, using each member\'s files'
  end

  team_name = ARGV.first
  team = Team.find team_name

  report_name = "team-#{unidown team_name}-report"
  report_source = "#{report_name}.adoc"
  output = "#{report_name}.html"

  [output, report_source].each do |file|
    File.delete file if File.exist? file
  end

  HORIZONTAL_RULE = "'''".freeze
  append_file(report_source, "= Team #{team_name.titlecase}\n\n")
  team.members_by_folder.each do |tm|
    append_file(report_source, "include::#{tm}/overview.adoc[]\n\n#{HORIZONTAL_RULE}\n\n")
  end

  system('asciidoctor', "-o#{output}", report_source)
  system('open', output) # for Mac, use "cmd /c" for Windows
end
