#!/usr/bin/env ruby

# Should do a './mt gen' before this to ensure overview files exist

require 'facets/string/titlecase'
require 'highline/import'
require 'shell'
require 'trollop'
require_relative 'lib/team'

class String
  def titleize
    split(/(\W)/).map(&:capitalize).join
  end
end

def append_file(destination, contents)
  open(destination, 'a') { |f|
    f.puts contents
    f.puts "\n"
  }
end

if __FILE__==$0
  opts = Trollop::options do
    banner "Create a report of a team, using each member's files"
  end

  team_name = ARGV[0]
  team = Team.find team_name

  report_name = "team-#{team_name.downcase}-report"
  report_source = "#{report_name}.adoc"
  output = "#{report_name}.html"

  [output, report_source].each do |file|
    File.delete file if File.exist? file
  end

  append_file(report_source, "= Team #{team_name.titleize}\n\n")
  team.members_by_folder.each do |e|
    append_file(report_source, "include::#{e}/overview.adoc[]\n\n'''\n\n")
  end

  system("asciidoctor", "-o#{output}", report_source)
  system("open", output) # for Mac, use "cmd /c" for Windows
end
