# frozen_string_literal: true

require 'fileutils'
require_relative 'employee'
require_relative 'employee_file'
require_relative 'file_writer'
require_relative 'observation_entry'

# Create a new entry for a person
class NewHireCommand
  include FileWriter

  def command(arguments)
    force = false
    if Array(arguments).first == '--force'
      force = true
      arguments.shift
    end

    team, first, last = arguments
    raise 'missing team argument' unless team
    raise 'missing first name argument' unless first
    raise 'missing last name argument' unless last

    employee = Employee.new(team: team, first: first, last: last)
    folder = EmployeeFolder.new employee
    folder.ensure_exists

    generate_overview_file_by(folder, force)
    generate_log_file_by(folder, force)
  end

  private

  def generate_file_by(folder, force, filename)
    content_file = EmployeeFile.new folder, filename
    print "\nReviewing #{content_file}... "
    if !force && File.exist?(content_file.path)
      print 'exists'
    else
      yield(content_file)
    end
    print "\n"
  end

  def generate_overview_file_by(folder, force)
    generate_file_by(folder, force, 'overview.adoc') do |content_file|
      create_overview_file folder, content_file
    end
  end

  def generate_log_file_by(folder, force)
    generate_file_by(folder, force, 'log.adoc') do |content_file|
      create_log_file content_file
    end
  end

  def create_overview_file(folder, overview_file)
    employee = folder.employee
    contents = <<~OVERVIEW
      :imagesdir: #{folder.path}

      == #{employee}

      image::headshot.jpg[#{employee}, width="200", align="right", float="right"]

      Team: #{employee.team.capitalize}

    OVERVIEW
    write_file(overview_file.path, contents)
    print 'created'
  end

  def create_log_file(log_file)
    log_file.ensure_exists
    contents = <<~CONTENTS
      === Biographical information

      === Employment information

      Hire Date:
      Grade level:
      ID:

    CONTENTS
    new_file_entry = ObservationEntry.new(content: 'File generated by new-hire command').render('File created')
    contents += new_file_entry
    write_file(log_file.path, contents)
    print 'created'
  end
end
