# frozen_string_literal: true
# # frozen_string_literal: true

# require 'asciidoctor'

# RSpec.describe do
#   it 'can analyze a document', skip: 'is a sandbox for analysis algorithm testing' do
#     lines = <<~LOG_FILE
#     === Biographical information

#     === Employment information

#     Start date::
#     Grade level:: Developer II
#     ID:

#     === File created (October  5, 2018,  9:53 AM)
#     Content::
#       File generated by new-hire command

#     === Observation (October  5, 2018,  9:53 AM)
#     Content::
#       Walked Vern down to payroll. Talked about our backgrounds. He worked for
#       Pollich, Lemke and Turcotte in Billings, another railroad company, then startup. Wanted to
#       move to Denver, so came to Wilderman Group. Went to Florida State, heard of from
#       Tampa office. Until Wilderman Group, all Java. Interviewed for Project One, then got
#       called back for .NET work.

#     === One-on-One (January 24, 2019, 12:00 AM)
#     Location::
#       Greg's office
#     Notes::
#       Career discussion, history with Pollich, Lemke and Turcotte in Billings, he was defensive
#       around proactivity comment I made about his team.
#     Actions::
#       none

#     === Observation (February 11, 2019, 12:00 PM)
#     Content::
#       Helped Vern with logging, structured messaging

#     === Paid time off (February 19, 2019, 12:00 PM)
#     Duration::
#       4 days
#     Start date:::
#       February 19, 2019
#     End date::
#       February 22, 2019
#     Reason::
#       vacation

#     === One-on-One (February 27, 2019, 12:00 AM)
#     Location::
#       unspecified
#     Notes::
#       Performance review (meets), goals: code samurai, consolidate documentation in Wiki
#     Actions::
#       none

#     === Multiple Member Note (March 15, 2019, 12:00 PM)
#     Applies to::
#       Drew Heidenreich, Mickey Gleichner, Roseann Breitenberg, Jefferson Heathcote, Eryn Schamberger,
#       Vern Corwin, Ronni D'Amore, Antionette Bins, Coralie Boyle
#     Note::
#       For one sprint, splitting the group into two Kanban teams. This group is the
#       feature team, who later dubbed themselves the Bears. Their charter is to
#       get all features done by GA.

#     === Observation (March 22, 2019, 12:00 PM)
#     Content::
#       Vern has been working on the #mentions feature back end. Happy he's on
#       Bears.

#     === Multiple Member Note (March 23, 2019, 10:00 AM)
#     Applies to::
#       Jefferson Heathcote, Roseann Breitenberg, Vern Corwin, Drew Heidenreich, Dustin Wiza, Ronni
#       D'Amore, Mickey Gleichner, Eryn Schamberger
#     Note::
#       The team came in to work today to try to catch up. So happy they all turned
#       out!

#     === Multiple Member Note (March 24, 2019,  1:46 PM)
#     Applies to::
#       Roseann Breitenberg, Ronni D'Amore, Vern Corwin
#     Note::
#       Breakfast at Syrup with my boss, Alonzo

#     === Observation (March 25, 2019,  3:11 PM)
#     Content::
#       Helped Vern with some regex

#     === Multiple Member Note (March 31, 2019, 12:00 PM)
#     Applies to::
#       Roseann Breitenberg, Vern Corwin, Coralie Boyle, Ronni D'Amore, Mickey Gleichner, Drew
#       Heidenreich, Dustin Wiza, Lanora Gutmann, Sherlene Volkman
#     Note::
#       Worked today.

#     === Multiple Member Note (April  4, 2019, 12:00 PM)
#     Applies to::
#       Vern Corwin, Sherlene Volkman
#     Note::
#       Both declined their 1:1s, no topics

#     === Observation (April 11, 2019, 12:00 PM)
#     Content::
#       Gave Vern his merit/VIP numbers, he wasn't impressed by the prorated merit
#       % increase.

#     === Multiple Member Note (April 11, 2019,  1:42 PM)
#     Applies to::
#       Goldie Pagac, Vern Corwin, Coralie Boyle, Ronni D'Amore
#     Note::
#       All were not present at work by 9am.

#     === Multiple Member Note (April 18, 2019,  9:00 AM)
#     Applies to::
#       Antionette Bins, Sabine Mohr, Drew Heidenreich, Leopoldo Turcotte, Jefferson Heathcote, Roseann
#       Breitenberg, Coralie Boyle, Vern Corwin, Goldie Pagac
#     Note::
#       All were late today. As of 9:10, Leopoldo and Roseann are still not here.

#     === One-on-One (April 18, 2019,  1:30 PM)
#     Location::
#       Palisade
#     Notes::
#       Discussed getting the project back to normal. Why my merit increase so low
#       (prorated), institutional memory of his accomplishments, incremental
#       increased here beyond annual review?
#     Actions::
#       none

#     === Paid time off (May  1, 2019, 12:00 PM)
#     Duration::
#       1 day
#     Start date:::
#       May  1, 2019
#     End date::
#       May  1, 2019
#     Reason::
#       vacation

#     === Observation (May  1, 2019, 12:00 PM)
#     Content::
#       Took PTO to ski, birthday was 4/30

#     === Observation (May 10, 2019, 12:00 PM)
#     Content::
#       In a 1:1, Eryn said Vern is acting more confident. He needs to be more
#       forward with his opinions. I asked Eryn to take a coaching role with
#       Vern, rather than directing him.

#     === Paid time off (May 29, 2019, 12:00 AM)
#     Start date:::
#       May 29, 2019
#     End date::
#       May 31, 2019
#     Reason::
#       vacation

#     === Observation (May 29, 2019, 12:00 PM)
#     Content::
#       On PTO until 5/31

#     === Paid time off (June  3, 2019, 12:00 AM)
#     Start date:::
#       June  3, 2019
#     End date::
#       June  3, 2019
#     Reason::
#       vacation

#     === Observation (June 13, 2019, 12:00 PM)
#     Content::
#       Vern was working an incident in the VerticalWeb IM channel, but didn't keep
#       the channel updated. Spoke to him about communication.

#     === Multiple Member Note (June 18, 2019, 12:00 PM)
#     Applies to::
#       Roseann Breitenberg, Nicole Keeling, Dustin Wiza, Vern Corwin
#     Note::
#       We played Betrayal at the House of the Hill after work in the Coffee Shop
#       break room

#     === One-on-One (June 19, 2019, 12:00 PM)
#     Location::
#       Palisade
#     Notes::
#       Vern is concerned about his career advancement opportunities. Had goal of
#       full-stack, will be harder on proposed team restructure. Pointed out I put
#       him on Mickey's team to help fast-track him; Mickey's our best mentor.
#     Actions::
#       none

#     === Observation (June 24, 2019, 12:00 PM)
#     Content::
#       From his perspective, he's waiting for Team Eagles to deliver repo implementations.
#       They don't want to create stubs. He also believes that Drew is
#       over-engineering.

#       Gave him the feedback that he's too indirect with his observations and
#       opinion. As a director, I don't have time to take his data and draw my own
#       conclusion. I need him to distill it into a recommendation. Lead with the
#       conclusion (BLUF).

#     === Observation (June 27, 2019,  5:00 AM)
#     Content::
#       Took point on updating our Pathfinder library, looking into licensing, reached
#       out to Mickey Stanier. Good initiative.

#     === Observation (June 30, 2019, 12:00 PM)
#     Applies to::
#       Vern Corwin, Antionette Bins, Dustin Wiza, Lanora Gutmann, Reginia Hammes, Phil
#       Wright, Mickey Gleichner, Jefferson Heathcote, Eryn Schamberger, Ronni D'Amore
#     Content::
#       Worked the weekend

#     === Paid time off (July  9, 2019,  8:44 AM)
#     Start date:::
#       July  9, 2019
#     End date::
#       July 10, 2019
#     Reason::
#       vacation

#     === Observation (July 13, 2019,  1:08 PM)
#     Applies to::
#       Mickey Gleichner, Roseann Breitenberg, Jefferson Heathcote, Oralee Haley, Coralie Boyle,
#       Sherlene Volkman, Vern Corwin
#     Content::
#       Worked on Saturday

#     === Observation (July 14, 2019, 12:00 PM)
#     Applies to::
#       Coralie Boyle, Sherlene Volkman, Goldie Pagac, Vern Corwin, Eryn Schamberger
#     Content::
#       Found out that the Panthers team has not been testing their code when
#       they tried to circumvent a build check. We're at 70% coverage now, which is
#       the minimum set by the tool. I'm displeased.

#     === Observation (July 16, 2019,  8:15 AM)
#     Content::
#       Brought up good point about database index impact on performance during
#       Phil's code review

#     === Paid time off (July 22, 2019,  8:42 AM)
#     Start date:::
#       July 22, 2019
#     End date::
#       July 22, 2019
#     Reason::
#       vacation

#     === One-on-One (August  9, 2019, 12:00 PM)
#     Location::
#       alcove
#     Notes::
#       Lots of questions about what comes after this release. Feedback about
#       Eryn, said he said junior developers are disposable. Said was disturbed about that
#       messaging.
#     Actions::
#       F/u with Eryn

#     === Observation (August 20, 2019,  8:49 PM)
#     Applies to::
#       Mickey Gleichner, Vern Corwin, Roseann Breitenberg, Dustin Wiza, Les Smith, Eryn
#       Schamberger
#     Content::
#       Worked late to get VerticalWeb 2019.8 through list of 33 defects in one day

#     === Observation (August 21, 2019,  9:48 PM)
#     Applies to::
#       Roseann Breitenberg, Erika Borer, Lanora Gutmann, Dustin Wiza, Jefferson Heathcote,
#       Eryn Schamberger, Mickey Gleichner, Vern Corwin, Ryan Bernier, Les Smith,
#       Toni Jackson
#     Content::
#       Present for the VerticalWeb 2019.8 release

#     === Observation (August 28, 2019, 11:28 AM)
#     Content::
#       Moving Vern Corwin to team Donkeys

#     === Team Meeting (December 10, 2019, 12:00 PM)
#     Attendees::
#       Vern Corwin, Coralie Boyle, Reginia Hammes, Jefferson Heathcote, Antionette Bins
#     Location::
#       Aspen
#     Notes::
#       Alonzo informed VerticalWeb teams that I will no longer be their manager. At
#       the beginning of the year, VerticalWeb is going down to one team. Remaining
#       team members will be distributed among other company products.
#     Actions::
#       none

#     === Observation (December 11, 2019, 11:12 AM)
#     Content::
#       Moving Vern Corwin to team Zzz_departed
#     LOG_FILE
#     doc = Asciidoctor::Document.new
#     reader = Asciidoctor::Reader.new lines
#     Asciidoctor::Parser.parse(reader, doc)

#     # require 'loofah'

#     entries = [ObservationEntry::NAME, OneOnOneEntry::NAME]
#     entries_regex = Regexp.union(entries)
#     content =  doc.sections
#       .filter{ |s| s.title =~ /#{entries_regex}/ }
#       .flat_map{ |s| s.content }
#       .map{ |c| c.tr("\n", ' ') }
#       .map{ |c| c.gsub(/\<.+?\>/, '') }
#       # .map{ |c| c =~ %r{<p>(.+)</p>\s*</dd>}m ? $1 : nil }
#       .first(10)

#     pp content

#     # content =  doc.sections
#     #   .filter{ |s| s.title =~ /Observation/ }
#     #   .flat_map{ |s| s.content }
#     #   .map{ |c| c =~ %r{<p>(.+)</p>}m ? $1.tr("\n", ' ') : nil }

#     # require 'sentimental'

#     # analyzer = Sentimental.new
#     # analyzer.load_defaults

#     # sentiments = content.reject(&:nil?).map{ |c| [c[0,50], analyzer.sentiment(c)] }.to_h

#     # pp sentiments

#     # analysis = content.reject(&:nil?).map{ |c| [c[0,50], analyzer.score(c)] }.to_h

#     # pp analysis

#     # expect(analysis).to be_nil
#   end
# end
